### ISSUE TITLE
Three problems with this Adapter

### ISSUE THREAD

**Issue by artem82** [soef/ioBroker.find-my-iphone#4]
Thanks for the Adapter!
Ver. 005
I have a few problems with this Adapter:
1) Adapter after some time frozen (dont work) - Dont  refresh a data. After restarting again works.
2) batteryLevel dont work, shows either 0% or 100%
3) After each request, a letter arrives from Apple ICloud: Your Apple ID was used to sign in to iCloud from a web browser. As there is problem number 1, my adapter restarts every 10 minutes and every 10 minutes I receive a email from Apple. 
I understand that the problem 3 is independent of the adapter developer, but maybe something to think of and somehow make the device associated with the iobroker adapter account.

Thanks!!!

**Comment by soef** [comment]
Hello, batterylevel ist fixed in Version 0.0.6.

The Adapter does not refresh the states frequently. To perform a refresh once, you can set the "refresh" state of a device or in the root to true. Then the adapter will update/refresh the appropriate device/devices one time. The reason is not to send too much calls to Apple. So refresh only when needed.

I hope this will help...
